### ISSUE TITLE
Add getting started, typical use case and install instructions to readme.md

### ISSUE THREAD

**Issue by arothuis** [bitbinio/bitbin#25]
It would attract more users (and devs) if it is more clear how bitbin is installed and used.

**Comment by cjsaylor** [comment]
:+1:

**Comment by cjsaylor** [comment]
@arothuis This has been added to the readme. Since only the `bitbin-local` adapter is currently implemented, the example follows that. Once we have more adapters (like S3), we will probably opt to that since that will be the more commonly used adapter.
